# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161018_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='docfile',
            field=models.FileField(default=datetime.datetime(2016, 10, 20, 11, 35, 28, 132269, tzinfo=utc), upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
